apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-role
  containers:
    - name: argocd
      image: artifactory.cloud.cms.gov/docker/argoproj/argocd@sha256:b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2
      command: ["cat"]
      tty: true
