apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 999
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: argocd
      image: artifactory.cloud.cms.gov/gi-gantuar-ironbank/ironbank/opensource/argoproj/argocd@sha256:77634fea0b7adf0503eb658bb1892db5d71aed8b3bf773cd373a0041fc3a05a7
      command: ["cat"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "500Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "500Mi"
