apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
  restartPolicy: Never
  volumes:
    - name: clamav-db
      emptyDir: {}
  containers:
    - name: clamav
      image: artifactory.cloud.cms.gov/gi-gantuar-ironbank/ironbank/opensource/clamav/clamav:1.5.3
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: clamav-db
          mountPath: /var/lib/clamav
      resources:
        requests:
          cpu: "2"
          memory: "5Gi"
          ephemeral-storage: "5Gi"
        limits:
          cpu: "2"
          memory: "5Gi"
          ephemeral-storage: "5Gi"
