apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: flux
      image: artifactory.cloud.cms.gov/docker/fluxcd/flux-cli@sha256:248a0520ff70894b39bc79960649293d937b5b7dc55376947a8bbc68dba7d71f
      command: ["cat"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "500Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
          ephemeral-storage: "500Mi"
