apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: gradle
      image: artifactory.cloud.cms.gov/gi-gantuar-ironbank/ironbank/opensource/gradle/gradle-jdk25@sha256:7880ef66d8c6d6f899f974ccc92f774d752d7e32cb17886bb6a4bca5c0637536
      command: ["cat"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "10Gi"
        limits:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "10Gi"
