apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: grype
      image: artifactory.cloud.cms.gov/docker/anchore/grype@sha256:166001ed93ae8463acad508c746586ced665abe9d817ae452ed9b781ddb6cebb
      command: ["cat"]
      tty: true
      env:
        - name: HOME
          value: "/home/jenkins/agent"
        - name: PATH
          value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/busybox:/"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
