apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: grype
      image: artifactory.cloud.cms.gov/docker/anchore/grype@sha256:8c2c9234a345577a6d321a4753aa3ee1276d8975c8452d2344a56b57733ecad3
      command: ["cat"]
      tty: true
      env:
        - name: HOME
          value: "/home/jenkins/agent"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
