apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1030
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: jfrog-cli
      image: artifactory.cloud.cms.gov/docker/jfrog/jfrog-cli-v2-jf@sha256:4b6f689bf0827e5897cbb2c30869af1a3d953d42336eb196be1664f0e8bdda58
      command: ["cat"]
      tty: true
      env:
        - name: PATH
          value: "/usr/local/bin:/usr/bin:/bin"
        - name: JFROG_CLI_HOME_DIR
          value: "/home/jenkins/agent/.jfrog"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
        limits:
          cpu: "500m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
