apiVersion: v1
kind: Pod
spec:
  containers:
    - name: node
      image: artifactory.cloud.cms.gov/docker/node@sha256:980c5420a7a2ddcb44037726977f2a349e5c7b64217516c7488dce4c74d71583
      command: ["cat"]
      tty: true
