apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-role
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: node
      image: artifactory.cloud.cms.gov/docker/node@sha256:980c5420a7a2ddcb44037726977f2a349e5c7b64217516c7488dce4c74d71583
      command: ["cat"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
