apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-role
  containers:
    - name: podman
      image: artifactory.cloud.cms.gov/docker/podman/stable@sha256:d6f571f9dba42c692281715f4402bdd78884ff16707b08293ebe4cfdea31dbcb
      command: ["cat"]
      tty: true
