apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
  restartPolicy: Never
  containers:
    - name: podman
      image: artifactory.cloud.cms.gov/docker/podman/stable@sha256:d6f571f9dba42c692281715f4402bdd78884ff16707b08293ebe4cfdea31dbcb
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "20Gi"
        limits:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "20Gi"
    - name: jfrog-cli
      image: artifactory.cloud.cms.gov/docker/jfrog/jfrog-cli-v2@sha256:fbdae2394788e1df2042a56c569ee118648f931796138313507498bb5b6d875c
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
        limits:
          cpu: "500m"
          memory: "512Mi"
          ephemeral-storage: "1Gi"
