apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-role
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
  restartPolicy: Never
  containers:
    - name: podman
      image: artifactory.cloud.cms.gov/docker/podman/stable@sha256:d6f571f9dba42c692281715f4402bdd78884ff16707b08293ebe4cfdea31dbcb
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "20Gi"
        limits:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "20Gi"
