apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: "true"
spec:
  serviceAccountName: jenkins-agents
  nodeSelector:
    node-pool: agent
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
    - name: renovate
      image: artifactory.cloud.cms.gov/docker/renovate/renovate@sha256:49a2e1229550eaacf111123f394d1f63b0608f05096b09af6056cc65e4cb8b54
      command: ["cat"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
          ephemeral-storage: "5Gi"
