apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-role
  containers:
    - name: snyk
      image: artifactory.cloud.cms.gov/docker/snyk/snyk@sha256:9d890769442afa9bd185403e7c199a60ea70b6784865e9ed0df2380f45e1c028
      command: ["cat"]
      tty: true
