pipeline {
  parameters {
    string(name: 'image', defaultValue: "${default_image}", description: 'The fully qualified container image name')
    string(name: 'tag', defaultValue: "${default_tag}", description: 'Container image tag')
  }

  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        restartPolicy: Never
        containers:
        - name: build
          image: alpine:3
          command: ['tail', '-f', '/dev/null']
      """
    }
  }

  stages {
    stage('Testing') {
      steps {
        container('build') {
          sh "echo Image param: ${image}"
          sh "echo Tag param: ${tag}"
        }
      }
    }
  }
}
